<?php
/**
 * @file
 * Functions related to event database pull module
 */

/**
 *  Implements hook_theme().
 */
function event_database_pull_theme($existing, $type, $theme, $path) {
  return [
    'event_database_pull_event_list' => [
      'variables' => [
        'events' => [],
        'view' => [],
        'images' => [],
      ],
    ],
    'event_database_pull_occurrences_list' => [
      'variables' => [
        'occurrences' => [],
        'view' => [],
        'images' => [],
        'searchBox' => [],
        'pager' => [],
      ],
    ],
    'event_database_pull_event_details' => [
      'variables' => [
        'event' => [],
        'image' => [],
      ],
    ],
    'event_database_pull_occurrence_details' => [
      'variables' => [
        'occurrence' => [],
        'image' => [],
      ],
    ],
    'event_database_pull_error' => [
      'variables' => [
        'message' => [],
      ],
    ],
    'event_database_block' => [
      'variables' => [
        'events' => [],
        'view' => [],
        'images' => [],
      ],
    ],
    'event_database_occurrences_block' => [
      'variables' => [
        'occurrences' => [],
        'view' => [],
        'images' => [],
      ],
    ],
    'event_database_block_error' => [
      'variables' => [
        'message' => [],
      ],
    ],
  ];
}